[shell]
program = "/Users/fran/.nix-profile/bin/fish"

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

[font]
normal.family = "JetBrains Mono" # FIXME: currently installed manually
normal.style = "Regular"
size = 20

[colors]
# manually setting background to match nvim
# used `:hi Normal` and used guibg value
primary.background = "#282828"
